Feature/data merge
energinet-singularity/gis-provider pull request #2
Opened 2022-05-09 08:03 UTC by stigsberg

**Description of your changes**

Category:

- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [ ] I have bumped all relevant version numbers
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my changes if this is needed
- [ ] I have described my changes in the "description of your changes" field
- [ ] I have tested this change on a running cluster 
- [ ] I have created/corrected automated tests related to the changes, if possible/necessary
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have squashed commits if necessary

2022-05-11 07:03 UTC, vjsaini75 commented on README.md
> +A container that parses three files and translated a name column from one file to the other. The last file is used to enforce a fixed translation instead of the one found by the script.
suggestion:- This codeset work as container to publish data from 3 files and column information to inter link data. 
The last file is used to enforce a fixed translation instead of the one found by the script. ( which one is last file)

2022-05-11 07:08 UTC, vjsaini75 commented on README.md
> +|GIS_FILENAME|Filename of the excel file that needs a column translated|GIS_Driftstr_luftledning_koordinater_decimalgrader_05042022.xls|
missing header

2022-05-11 07:08 UTC, vjsaini75 commented on README.md
> +|ETS_COLUMN_DLR_ENABLED|The column that controls if a name is needed for the later application|DLR_ENABLED|
missing header

2022-05-11 07:10 UTC, swedchef requested changes
NOTE: README, main.py and test_Script.py have NOT been review to end.

My overall take is very positive - quite clean code, well documented, good naming etc.

I have added comments that are in my opinion necessary, but most are suggestions for improvements, or just alternative ways of tackling the same issues. You will have to be critical (and open) and choose what is the best solution. Ask if i have been unclear anywhere.

2022-05-11 07:14 UTC, stigsberg commented on .gitignore
> +**/.vscode
Thanks it is done.

2022-05-11 07:21 UTC, stigsberg commented on chart/templates/deployment.yaml
> +piVersion: apps/v1
Included

2022-05-11 07:22 UTC, stigsberg commented on chart/templates/pvc.yaml
> +---
You are probably right, removed.

2022-05-11 07:25 UTC, vjsaini75 commented on README.md
> +One excel file containing the name that needs to be translated to match the name in the other csv file.
Needs Newline or enter to make separate lines at present it appear as one paragraph, withput line break.

2022-05-11 07:33 UTC, vjsaini75 commented on README.md
> +In addition there is another file that can be transfared to the volume. The purpose of the files is to have the option to bypass the result of the translation function, if the name did not translate
little confusion on name,
which name :- can you write or line_name, or text from column

2022-05-11 07:36 UTC, stigsberg commented on app/requirements.txt
> +xlrd>=1.0.0
They are packages that support the pandas library. For some reason it does not itself import these dependencies.
Therefore the container will crash without them in the requirements.txt.
Suggestion refused.

2022-05-11 07:38 UTC, vjsaini75 commented on README.md
> +One csv file that holds the translated name plus any other column that you want to translate the name to.
One csv file that holds the translated name  ( from which column , which file) plus any other column that you want to translate the name to.

2022-05-11 07:56 UTC, stigsberg commented on app/main.py
> +    gis_names = np.unique(gis_dataframe[gis_column].tolist())
Good idear to use the build in pandas functions instead of np.
I've changed the code to reflect the idear.

2022-05-11 08:20 UTC, stigsberg commented on app/main.py
> +        log.info('Alle names from the GIS file have been translated.')
Included

2022-05-11 08:39 UTC, stigsberg commented on app/main.py
> +    '''
Included most of the suggestion but corrected a few things.

2022-05-11 08:40 UTC, stigsberg commented on README.md
> +A container that parses three files and translated a name column from one file to the other. The last file is used to enforce a fixed translation instead of the one found by the script.
Included

2022-05-11 08:40 UTC, stigsberg commented on README.md
> +|GIS_FILENAME|Filename of the excel file that needs a column translated|GIS_Driftstr_luftledning_koordinater_decimalgrader_05042022.xls|
fixed

2022-05-11 08:41 UTC, stigsberg commented on README.md
> +|ETS_COLUMN_DLR_ENABLED|The column that controls if a name is needed for the later application|DLR_ENABLED|
fixed

2022-05-11 08:44 UTC, stigsberg commented on README.md
> +One excel file containing the name that needs to be translated to match the name in the other csv file.
fixed

2022-05-11 09:24 UTC, stigsberg commented on README.md
> +In addition there is another file that can be transfared to the volume. The purpose of the files is to have the option to bypass the result of the translation function, if the name did not translate
rewrote the section

2022-05-11 09:25 UTC, stigsberg commented on README.md
> +One csv file that holds the translated name plus any other column that you want to translate the name to.
rewrote the section. :)

2022-05-11 09:53 UTC, vjsaini75 commented on README.md
> +The input to the container is three files where one is optional these are:
sugession , replace "is three files" with "are three files " :)

2022-05-11 10:01 UTC, swedchef requested changes
Done with main.py for now. Will re-review when you are done with the suggestions you have had so far.

2022-05-11 10:01 UTC, swedchef commented on app/main.py
> +        log.info("I am still alive!")
You have multiple info-messages on each run, so this heartbeat is really not needed.

2022-05-11 10:52 UTC, swedchef commented on app/requirements.txt
> +xlrd>=1.0.0
Would like if pandas had an option to install extras like many other packages do - but it seems they don't support that. Annoying and strange. Oh well. Nothing to do then.

2022-05-11 11:31 UTC, vjsaini75 approved these changes

2022-05-11 11:40 UTC, stigsberg commented on app/main.py
> +                                'Ensure that there is no need for mapping names.')
Yes, i've created it so that the enforcement of a specific mapping is an optional thing.

2022-05-11 13:13 UTC, stigsberg commented on app/main.py
> +    translated_gis_dataframe = temp_gis_dataframe.replace({new_column_name: ets_name_to_mrid})
Nice input, i took the idear and changed to dictionary comprehension.

2022-05-11 13:27 UTC, stigsberg commented on app/main.py
> +MOCK_DATA = environ.get('MOCK_DATA', 'True')
It should of course be set to False, it's a leftover from development

2022-05-11 13:27 UTC, stigsberg commented on app/main.py
> +# GIS_FILEPATH = MRID_FILEPATH = MAP_FILEPATH = path.dirname(__file__) + '/../real-data/'
When it's all done :)

2022-05-11 13:27 UTC, stigsberg commented on app/main.py
> +    # GIS_FILEPATH = MRID_FILEPATH = path.dirname(__file__) + '/../tests/valid-testdata/'
When it's all done :)

2022-05-12 05:52 UTC, swedchef commented on chart/templates/deployment.yaml
> +              protocol: TCP
I don't get this - what is port 80 for?

2022-05-12 09:41 UTC, stigsberg commented on app/main.py
> +        dataframe.drop(dataframe.head(1).index, inplace=True)
Changed the name of the function.

2022-05-12 12:01 UTC, stigsberg commented on app/main.py
> +        dict_set = dataframe.set_index(dict_key).to_dict()[dict_value]
I've done it this way to represent the flow of going from dataframe to a dictionary with the key specified, for the dictionary value in the end.

2022-05-12 13:51 UTC, stigsberg commented on Dockerfile
> +EXPOSE ${API_PORT}
We talked it over and agreed to add it to issues since there is some value to be able to combine this port with the port on the script.

2022-05-16 12:56 UTC, swedchef requested changes
There we go!

2022-05-16 12:56 UTC, swedchef commented on README.md
> +|MAP_COLUMN_GIS_NAME|Column wit existing name in the excel file|GIS Name|
```suggestion
|MAP_COLUMN_GIS_NAME|Name of the column containing GIS name|GIS Name|
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +|MAP_COLUMN_ETS_NAME|Column that state the new name|ETS Name|
```suggestion
|MAP_COLUMN_ETS_NAME|Name of the column containing ETS name|ETS Name|
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +|MOCK_DATA|Parameter to control the use of Mock Data|False|
Why is this here as a separate thing? Please join it with the rest - and add DEBUG as well (check earlier suggestion)

2022-05-16 12:56 UTC, swedchef commented on README.md
> +
```suggestion
The script takes three files as input:
- The GIS excel file
- The ETS csv file containing ETS name, MRID and enabled (Yes/No) state for each line
- A mapping/translation file for forced translation of specific names (this file is optional)

For more information on how the files are structured please look into the tests/valid-testdata folder that is supplied in the repository.

```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +The output will be a API that you will be able to SQL to and get information in the enriched GIS dataframe.
```suggestion
The output will be an API that can be queried with SQL to get information from the enriched GIS dataframe.
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +* Custime python module, available here: https://github.com/energinet-singularity/singupy
```suggestion
* Custom 'singupy' python module, available here: https://github.com/energinet-singularity/singupy
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +* To run the script without mock data enabled. The user needs to be able to push files into the created volume on their system.
```suggestion
* The files mentioned under "Input". It is possible to mock a set of input files with the MOCK_DATA environment variable.
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +### Python (if not run as part of the container)
```suggestion
#### Python (if not run as part of the container)
```
This is supposed to be a sub-heading below dependencies

2022-05-16 12:56 UTC, swedchef commented on README.md
> +### HELM (only relevant if using HELM for deployment)
```suggestion
#### HELM (only relevant if using HELM for deployment)
```
This is supposed to be a sub-heading below dependencies

2022-05-16 12:56 UTC, swedchef commented on README.md
> +### Docker
```suggestion
#### Docker
```
This is supposed to be a sub-heading below dependencies

Why did you move this? I think it is better if we follow the template in stead of moving items around.

2022-05-16 12:56 UTC, swedchef commented on README.md
> +## Running container
```suggestion
### Running container
```
This is supposed to be a sub-heading below getting started

2022-05-16 12:56 UTC, swedchef commented on README.md
> +### Using own data source
```suggestion
#### Using own data source
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +### Using mock data
```suggestion
#### Using mock data
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +### SQL commands
```suggestion
#### SQL commands
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +The container will now be running interactively and you will be able to see the log output while the container runs through the mock data build into the Dockerfile. While using mock data there is no
```suggestion
The container will now be running interactively and you will be able to see the log output while the container runs.
```
I would suggest shortening it down to this.

2022-05-16 12:56 UTC, swedchef commented on README.md
> + curl -d '{"sql-query": "SELECT * FROM GIS_DATA;"}' -H 'Content-Type: application/json' -X POST http://localhost:5110/
```suggestion
````bash
 curl -d '{"sql-query": "SELECT * FROM GIS_DATA;"}' -H 'Content-Type: application/json' -X POST http://localhost:5000/
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> + curl -d '{"sql-query": "SELECT * FROM GIS_DATA;"}' -H 'Content-Type: application/json' -X POST http://localhost:5110/
removed "sql statement" text and fixed port

2022-05-16 12:56 UTC, swedchef commented on README.md
> +For more information regarding the API setup and structure i refer to the custom module at https://github.com/energinet-singularity/singupy
```suggestion
For more information regarding the API setup and structure, refer to the custom module at https://github.com/energinet-singularity/singupy
```

2022-05-16 12:56 UTC, swedchef commented on README.md
> +* 0.0.2:
Assume this should be 1.0.0 when we move to production, as per you own comment?

2022-05-17 10:56 UTC, stigsberg commented on app/main.py
> +        Well.. it was missing so i just kind of added it without really getting what it does..
Sorry it was a suggestion so took the input raw. :)

2022-05-17 11:25 UTC, stigsberg commented on README.md
> +### Mapping variables to create a another layer of translating
I think we need to talk about this since I am unsure if I made myself clear was this file is used for.

2022-05-20 11:45 UTC, swedchef approved these changes
Please go through the comments. I don't think there is anything breaking, but some issues remain.

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +def map_gis_to_ets_line_name(gis_dataframe: pd.DataFrame, gis_column: str, regex: str) -> dict:
Type hint for output/return is incorrect

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +    gis_dataframe[gis_column] = gis_dataframe[gis_column].str.replace(" ", "")
Be aware - this will only replace space, not other white-space characters.

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +            # The restructed name matching the syntax of the desired name
This sentence is not really a sentence. And do you mean restructured ??

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +    ets_name_to_mrid: dict
```suggestion
    ets_name_to_mrid: dict[str, str]
```
I assume?

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +        None
```suggestion
    None
```
I think the correct procedure when there is no return is actually to just skip the Returns section - but if you leave it, there is no indentation under headers.

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +    gis_line_name_to_ets_line_name: dict
```suggestion
    gis_line_name_to_ets_line_name: dict[str, str]
```

2022-05-20 11:45 UTC, swedchef commented on app/main.py
> +            log.warning(f'Files not found at: "{GIS_FILEPATH}" and "{MRID_FILEPATH}"')
I would argue this is not a warning, but at least an error.

2022-05-20 12:12 UTC, stigsberg commented on app/main.py
> +from singupy.conversion import kv_to_letter
I agree the name gets wierd when a import of the lib is done. 
But I do not agree that this should be fixed in the user application but rather in the lib its imported from.

2022-05-25 08:47 UTC, swedchef approved these changes
GREAT!

2022-05-25 09:04 UTC, swedchef commented on app/main.py
> +from singupy.conversion import kv_to_letter
I get what you are saying - but i disagree. In general i would argue that it is handled by how you decide to import the module. You are importing the specific function rather than the entire parent-module, which would solve the issue of logical naming.
````
from singupy import conversion
xx = conversion.kv_to_letter(yy)
````
Similarly, you don't import "get" from os.environ, as that would leave you with a oddly named function (simply "get") that is hard to determine what does - you take the entire "environ" module, so that you can call "environ.get" which is much more explanatory. By your logic, the "get" function of the "environ" submodule would have to be named "get_environ_os" or similarly, which would mean people importing the entire module would have to write "os.environ_os.get_environ_os" or something like that, which - well, i guess you already see what i am getting at.

2022-05-25 11:30 UTC, stigsberg commented on app/main.py
> +from singupy.conversion import kv_to_letter
You argument is very valid! :)

2022-05-25 11:49 UTC, merged